In [1]:
import numpy as np

In [2]:
months = [str(x).zfill(2) for x in range(1, 13)]
m = np.array(months)
print(m, m.ndim, m.shape, m.dtype, m.size, m.data)
a = np.arange(30, dtype=np.int64)
print(a, a.ndim, a.shape, a.dtype, a.size, a.data)


['01' '02' '03' '04' '05' '06' '07' '08' '09' '10' '11' '12'] 1 (12,) <U2 12 <memory at 0x000001747CDFEE80>
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] 1 (30,) int64 30 <memory at 0x000001747CDFEE80>


In [4]:
b = a.reshape(2, 3, 5)
print(b, b.ndim, b.shape)



[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]] 3 (2, 3, 5)


In [5]:
f = np.arange(4, dtype=np.int64)
ft = f.T
print(f.dot(ft))
print(f.shape, ft.shape)

14
(4,) (4,)


In [7]:
g = f[np.newaxis, :]
h = f[:, np.newaxis]
print(f, f.shape)
print(g, g.shape)
print(h, h.shape)
print("g:", [g < 2])
print("g:", g[g < 2])
print("h:", [h < 2])
print("h:", h[h < 2])


[0 1 2 3] (4,)
[[0 1 2 3]] (1, 4)
[[0]
 [1]
 [2]
 [3]] (4, 1)
g: [array([[ True,  True, False, False]])]
g: [0 1]
h: [array([[ True],
       [ True],
       [False],
       [False]])]
h: [0 1]


In [8]:
print(g @ h)
print(h @ g)
print(f.dot(f))
print(f @ f)

[[14]]
[[0 0 0 0]
 [0 1 2 3]
 [0 2 4 6]
 [0 3 6 9]]
14
14


In [9]:
m = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10],
                [4, 5, 6, 7, 8],
                [8, 9, 10, 11, 12],
                [13, 14, 15, 16, 17]])
revm = m[::,::-1]
print(revm)
revmrow = m[::-1,:]
print(revmrow)
revmall = m[::-1,::-1]
print(revmall)
cut = m[1:-1,1:-1]
print(cut)

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [ 8  7  6  5  4]
 [12 11 10  9  8]
 [17 16 15 14 13]]
[[13 14 15 16 17]
 [ 8  9 10 11 12]
 [ 4  5  6  7  8]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]
[[17 16 15 14 13]
 [12 11 10  9  8]
 [ 8  7  6  5  4]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]
[[ 7  8  9]
 [ 5  6  7]
 [ 9 10 11]]
